// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maysavtlhrxfvcnqtopa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heXNhdnRsaHJ4ZnZjbnF0b3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjE5MjcsImV4cCI6MjA2ODQzNzkyN30.62C2LjrYH3sa6tHHbPyHRk8KdjZHwOjgtzGuxrFn6aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});